
cellIdPreamble: ""

data:
  test:
    query: vector(1)
    datasourceUid: e5ebe0e3-4d0e-4311-8bdf-bbba2133fcf1

cells:
  cell-DC1-8500L-IE:
    dataRef: test

    fillColor:
      thresholds:
        - { level: 0, color: "red" }
        - { level: 1, color: "green" }
